# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/3.3.0/bin/cmake

# The command to remove a file.
RM = /opt/cmake/3.3.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/userspace/ajs224/Dropbox/Code/MFATree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/userspace/ajs224/Dropbox/Code/MFATree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/cmake/3.3.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake/3.3.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/3.3.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/userspace/ajs224/Dropbox/Code/MFATree/CMakeFiles /home/userspace/ajs224/Dropbox/Code/MFATree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/userspace/ajs224/Dropbox/Code/MFATree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mfa-c++

# Build rule for target.
mfa-c++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mfa-c++
.PHONY : mfa-c++

# fast build rule for target.
mfa-c++/fast:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/build
.PHONY : mfa-c++/fast

source/Particle.o: source/Particle.c++.o

.PHONY : source/Particle.o

# target to build an object file
source/Particle.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/Particle.c++.o
.PHONY : source/Particle.c++.o

source/Particle.i: source/Particle.c++.i

.PHONY : source/Particle.i

# target to preprocess a source file
source/Particle.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/Particle.c++.i
.PHONY : source/Particle.c++.i

source/Particle.s: source/Particle.c++.s

.PHONY : source/Particle.s

# target to generate assembly for a file
source/Particle.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/Particle.c++.s
.PHONY : source/Particle.c++.s

source/m_in.o: source/m_in.c++.o

.PHONY : source/m_in.o

# target to build an object file
source/m_in.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/m_in.c++.o
.PHONY : source/m_in.c++.o

source/m_in.i: source/m_in.c++.i

.PHONY : source/m_in.i

# target to preprocess a source file
source/m_in.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/m_in.c++.i
.PHONY : source/m_in.c++.i

source/m_in.s: source/m_in.c++.s

.PHONY : source/m_in.s

# target to generate assembly for a file
source/m_in.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/m_in.c++.s
.PHONY : source/m_in.c++.s

source/mfa.o: source/mfa.c++.o

.PHONY : source/mfa.o

# target to build an object file
source/mfa.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/mfa.c++.o
.PHONY : source/mfa.c++.o

source/mfa.i: source/mfa.c++.i

.PHONY : source/mfa.i

# target to preprocess a source file
source/mfa.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/mfa.c++.i
.PHONY : source/mfa.c++.i

source/mfa.s: source/mfa.c++.s

.PHONY : source/mfa.s

# target to generate assembly for a file
source/mfa.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/mfa.c++.s
.PHONY : source/mfa.c++.s

source/mfa_params.o: source/mfa_params.c++.o

.PHONY : source/mfa_params.o

# target to build an object file
source/mfa_params.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/mfa_params.c++.o
.PHONY : source/mfa_params.c++.o

source/mfa_params.i: source/mfa_params.c++.i

.PHONY : source/mfa_params.i

# target to preprocess a source file
source/mfa_params.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/mfa_params.c++.i
.PHONY : source/mfa_params.c++.i

source/mfa_params.s: source/mfa_params.c++.s

.PHONY : source/mfa_params.s

# target to generate assembly for a file
source/mfa_params.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/mfa_params.c++.s
.PHONY : source/mfa_params.c++.s

source/moments.o: source/moments.c++.o

.PHONY : source/moments.o

# target to build an object file
source/moments.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/moments.c++.o
.PHONY : source/moments.c++.o

source/moments.i: source/moments.c++.i

.PHONY : source/moments.i

# target to preprocess a source file
source/moments.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/moments.c++.i
.PHONY : source/moments.c++.i

source/moments.s: source/moments.c++.s

.PHONY : source/moments.s

# target to generate assembly for a file
source/moments.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/moments.c++.s
.PHONY : source/moments.c++.s

source/parse_args.o: source/parse_args.c++.o

.PHONY : source/parse_args.o

# target to build an object file
source/parse_args.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/parse_args.c++.o
.PHONY : source/parse_args.c++.o

source/parse_args.i: source/parse_args.c++.i

.PHONY : source/parse_args.i

# target to preprocess a source file
source/parse_args.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/parse_args.c++.i
.PHONY : source/parse_args.c++.i

source/parse_args.s: source/parse_args.c++.s

.PHONY : source/parse_args.s

# target to generate assembly for a file
source/parse_args.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/parse_args.c++.s
.PHONY : source/parse_args.c++.s

source/random.o: source/random.c++.o

.PHONY : source/random.o

# target to build an object file
source/random.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/random.c++.o
.PHONY : source/random.c++.o

source/random.i: source/random.c++.i

.PHONY : source/random.i

# target to preprocess a source file
source/random.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/random.c++.i
.PHONY : source/random.c++.i

source/random.s: source/random.c++.s

.PHONY : source/random.s

# target to generate assembly for a file
source/random.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/random.c++.s
.PHONY : source/random.c++.s

source/theta.o: source/theta.c++.o

.PHONY : source/theta.o

# target to build an object file
source/theta.c++.o:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/theta.c++.o
.PHONY : source/theta.c++.o

source/theta.i: source/theta.c++.i

.PHONY : source/theta.i

# target to preprocess a source file
source/theta.c++.i:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/theta.c++.i
.PHONY : source/theta.c++.i

source/theta.s: source/theta.c++.s

.PHONY : source/theta.s

# target to generate assembly for a file
source/theta.c++.s:
	$(MAKE) -f CMakeFiles/mfa-c++.dir/build.make CMakeFiles/mfa-c++.dir/source/theta.c++.s
.PHONY : source/theta.c++.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mfa-c++"
	@echo "... source/Particle.o"
	@echo "... source/Particle.i"
	@echo "... source/Particle.s"
	@echo "... source/m_in.o"
	@echo "... source/m_in.i"
	@echo "... source/m_in.s"
	@echo "... source/mfa.o"
	@echo "... source/mfa.i"
	@echo "... source/mfa.s"
	@echo "... source/mfa_params.o"
	@echo "... source/mfa_params.i"
	@echo "... source/mfa_params.s"
	@echo "... source/moments.o"
	@echo "... source/moments.i"
	@echo "... source/moments.s"
	@echo "... source/parse_args.o"
	@echo "... source/parse_args.i"
	@echo "... source/parse_args.s"
	@echo "... source/random.o"
	@echo "... source/random.i"
	@echo "... source/random.s"
	@echo "... source/theta.o"
	@echo "... source/theta.i"
	@echo "... source/theta.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

